---
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.4.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
    - id: tests
      name: tests
      entry: sh scripts/test.sh
      language: system
