#pragma once

#define DEFAULT_STORAGE_TYPE (0) // LIST_BLOCKS
#define DEFAULT_EMPTY_DB_ZERO_PAGES_COUNT (1)

#define DEFAULT_PAGE_SIZE (4096)
#define MAX_PAGE_SIZE (16384)

#define DEFAULT_MAX_CACHED_PAGES_COUNT (1024)
